import "./globals.css";
// import Header from  "../components/header&footer/Header.jsx"
// import Footer from  "../components/header&footer/Footer.jsx"

export const metadata = {
  title: "Physiohub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        
      </body>
    </html>
  );
}
